#!/bin/sh
if [ -z "$1" ]; then
    /usr/bin/bash /opt/nebula/core/bin/error
    exit 22
fi
echo "[Nebula] Stopping ${1}..."
sudo docker-compose --file /srv/nebula/${1}/docker-compose.yml --env-file /srv/nebula/${1}/.nebula.env down